import 'models/product_model.dart';

final List<Product> allProducts = [
  // 1. 건성 피부 제품
  Product(
    id: 1,
    name: '라네즈 크림스킨',
    imageUrl: 'https://thumbnail1.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/d027/a7b5e3491d038d2ba2275247975f17d49f3e52411a5136613baba1762c34.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7hXW',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_1',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 2,
    name: '이솔 프로폴리스 세럼',
    imageUrl: 'https://thumbnail9.coupangcdn.com/thumbnails/remote/320x320ex/image/retail/images/5617110828242400-5e263933-b7d0-4130-ad67-543518a0c856.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7ndH',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_2',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 3,
    name: '프리메라 알파인베리 워터리크림',
    imageUrl: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/548431605420423-c1e7ae36-222a-47dc-be4c-f159cd2eebaf.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7ouA',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_3',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 4,
    name: '피지오겔 DMT페이셜 크림',
    imageUrl: 'https://thumbnail9.coupangcdn.com/thumbnails/remote/320x320ex/image/retail/images/159639472522302-8df44f6d-de20-4f92-b575-8e3e51e71fc3.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7qPR',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_4',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 5,
    name: '닥터자르트 시카페어 크림',
    imageUrl: 'https://t2c.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/5298882781245730-c23e5680-6f7d-4281-8bf0-0f558b0b5739.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7rr8',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_5',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 6,
    name: '더마토리 촉촉 수분크림',
    imageUrl: 'https://thumbnail13.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/2a74/1bd0252e8a806cfe656cb7d0cdd3fb79afd721abf5f9bc460ae1e2398ea0.png',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM7rWN',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_6',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 7,
    name: 'Cetaphil Daily Hydrating Lotion',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3HViIIb',
    recommendationKey: 'rec_7',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 8,
    name: 'Belif The True Cream Moisturizing Bomb',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4mBRaXn',
    recommendationKey: 'rec_8',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 9,
    name: 'Neutrogena Hydro Boost Water Gel',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4g4qlIP',
    recommendationKey: 'rec_9',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 10,
    name: 'Vanicream Moisturizing Skin Cream',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/41vEaKv',
    recommendationKey: 'rec_10',
    attributes: {'skinType': 'dry'},
  ),
  Product(
    id: 11,
    name: 'La Roche-Posay Lipikar Balm AP+',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/45YL1gR',
    recommendationKey: 'rec_11',
    attributes: {'skinType': 'dry'},
  ),
  // 2. 여드름/트러블 피부 제품
  Product(
    id: 12,
    name: '닥터지 레드 블레미쉬 클리어 수딩 크림',
    imageUrl: 'https://thumbnail14.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/image_audit/stage/manual/3c1d5ec6-0aea-4087-8bf8-92b8e589a552_1750659497348.jpeg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM71k9',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_12',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 13,
    name: '어니언 앰플',
    imageUrl: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/38124538520974-880737f4-56d1-4744-b640-cd12ed2cbc2b.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM71O7',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_13',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 14,
    name: '메디힐 티트리 세럼',
    imageUrl: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/320x320ex/image/retail/images/2025/02/04/10/4/faf8eb2c-6578-4d84-821a-0a518eac0231.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM72wM',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_14',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 15,
    name: '닥터포헤어 트러블 진정 토너',
    imageUrl: 'https://t5a.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/79c0/cc51bdcc3b5756ddafb45125dba4710e577adacbe5f81c72bcb49a5c0f32.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM72YB',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_15',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 16,
    name: 'La Roche-Posay Effaclar Medicated Gel Cleanser',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3K0mIHR',
    recommendationKey: 'rec_16',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 17,
    name: 'IZDUM 여드름 패치',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/45XKqMd',
    recommendationKey: 'rec_17',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 18,
    name: 'Paula’s Choice BHA Exfoliant',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/45Gx0FI',
    recommendationKey: 'rec_18',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 19,
    name: 'COSRX Acne Pimple Master Patch',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/45KTjdr',
    recommendationKey: 'rec_19',
    attributes: {'skinType': 'acne'},
  ),
  Product(
    id: 20,
    name: 'Murad Clarifying Cleanser',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3HNq9RJ',
    recommendationKey: 'rec_20',
    attributes: {'skinType': 'acne'},
  ),
  // 3. 민감성/저자극 피부 제품
  Product(
    id: 21,
    name: '닥터지 레드 블레미쉬 클리어 수딩 크림',
    imageUrl: 'https://t5a.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/image_audit/stage/manual/3c1d5ec6-0aea-4087-8bf8-92b8e589a552_1750659497348.jpeg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8kFp',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_21',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 22,
    name: '에즈윤 저자극 클렌저',
    imageUrl: '',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8k7k',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_22',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 23,
    name: '이니스프리 그린티 씨드 세럼',
    imageUrl: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/549898109258293-3df9f041-3b03-40ab-8b2e-2771d58c2a75.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8tzR',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_23',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 24,
    name: 'CeraVe Hydrating Cleanser',
    imageUrl: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/6fb2/5c9ccf401c5da79db6369d969b9cc58356e28c79aa83f81ed1d25f844af4.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8t7r',
    affiliateUrlAmazon: 'https://amzn.to/45TLCQU',
    recommendationKey: 'rec_24',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 25,
    name: '아벤느 시칼파트 밤',
    imageUrl: 'https://thumbnail11.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/d09d/92918470ee67862dfd5587f78142d3eab0c24a0635d9d7f66bd7a417c8f7.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8uxM',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_25',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 26,
    name: 'CeraVe Moisturizing Cream',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/45TLCQU',
    recommendationKey: 'rec_26',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 27,
    name: '아이보스킨 인텐시브 시카 리페어 크림',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/41vQASu',
    recommendationKey: 'rec_27',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 28,
    name: 'Vanicream Gentle Facial Cleanser',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4p2iVda',
    recommendationKey: 'rec_28',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 29,
    name: 'La Roche-Posay Toleriane Ultra',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3UUx5iN',
    recommendationKey: 'rec_29',
    attributes: {'skinType': 'sensitive'},
  ),
  Product(
    id: 30,
    name: 'Bioderma Sensibio H2O Micellar Water',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3I02Wvy',
    recommendationKey: 'rec_30',
    attributes: {'skinType': 'sensitive'},
  ),
  // 4. 모공/각질 케어 제품
  Product(
    id: 31,
    name: '더마토리 트러블 모공 클리어 패드',
    imageUrl: 'https://thumbnail4.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/143b/f70806a609ba4ae26455be40e33f134302e3bff64be859a795537e579ea6.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8u1U',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_31',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 32,
    name: '코스알엑스 더 레티놀 0.1/0.3 크림',
    imageUrl: 'https://thumbnail13.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/2023/07/03/11/0/86bcb40a-c8b7-40b4-8371-9e3b0c551fcf.png',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8viK',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_32',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 33,
    name: '스킨푸드 블랙슈가 페이셜 스크럽',
    imageUrl: 'https://thumbnail1.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/160040715031656-2954b573-0292-4c71-9ebc-cffaaf865881.png',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8vGp',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_33',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 34,
    name: '닥터자르트 바이탈 하이드라 솔루션 토너',
    imageUrl: 'https://thumbnail2.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/159528746237335-125e370c-9639-4b8b-929a-692732bab845.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8v3x',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_34',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 35,
    name: 'MediCube Zero Pore Pad',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4p35lGC',
    recommendationKey: 'rec_35',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 36,
    name: 'Collagen Pore Skincare Set',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3JEGbhi',
    recommendationKey: 'rec_36',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 37,
    name: 'Paula’s Choice Skin Perfecting 2% BHA Liquid Exfoliant',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3URaxj1',
    recommendationKey: 'rec_37',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 38,
    name: 'First Aid Beauty Facial Radiance Pads',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3JDUBON',
    recommendationKey: 'rec_38',
    attributes: {'skinType': 'pore'},
  ),
  Product(
    id: 39,
    name: 'Neogen Dermalogy Bio-Peel Gauze Peeling Green Tea',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4g8buNM',
    recommendationKey: 'rec_39',
    attributes: {'skinType': 'pore'},
  ),
  // 5. 주름/탄력/칙칙함 개선 제품
  Product(
    id: 40,
    name: '미샤 타임레볼루션 나이트 리페어 앰플',
    imageUrl: 'https://thumbnail2.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/4694/e4bb755bc59ec606f4453d6498a092bf272f299b90d0d3ec79ebf9690cfb.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8Zdv',
    affiliateUrlAmazon: 'https://amzn.to/41xwdEv',
    recommendationKey: 'rec_40',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 41,
    name: '고기능성 안티에이징 앰플/크림',
    imageUrl: '',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8Zo4',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_41',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 42,
    name: '아이오페 바이오 에센스',
    imageUrl: 'https://t3a.coupangcdn.com/thumbnails/remote/212x212ex/image/vendor_inventory/c039/bb9ef8f9e077665acbafcb8dadaaaa80578948a912b6789f1b0d1a9c25df.jpg',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM8Z4z',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_42',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 43,
    name: '랩시리즈 링클 코렉터',
    imageUrl: 'https://thumbnail7.coupangcdn.com/thumbnails/remote/212x212ex/image/retail/images/2024/02/20/12/9/0eeff30f-7951-4263-aa68-15906590429d.png',
    affiliateUrlCoupang: 'https://link.coupang.com/a/cM80io',
    affiliateUrlAmazon: '',
    recommendationKey: 'rec_43',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 44,
    name: 'Missha Time Revolution Ampoule',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/41xwdEv',
    recommendationKey: 'rec_44',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 45,
    name: 'Dermarfirm Bakuchiol Retinol Serum',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/4648XPT',
    recommendationKey: 'rec_45',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 46,
    name: 'Olay Regenerist Micro-Sculpting Cream',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3JMEsXb',
    recommendationKey: 'rec_46',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 47,
    name: 'The Ordinary Buffet Multi-Technology Peptide Serum',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/3JEDqfY',
    recommendationKey: 'rec_47',
    attributes: {'skinType': 'anti-aging'},
  ),
  Product(
    id: 48,
    name: 'Kiehl’s Powerful-Strength Line-Reducing Concentrate',
    imageUrl: '',
    affiliateUrlCoupang: '',
    affiliateUrlAmazon: 'https://amzn.to/41vFIUI',
    recommendationKey: 'rec_48',
    attributes: {'skinType': 'anti-aging'},
  ),
];
